container:
  image: tensorflow/tensorflow:nightly-devel
  cpu: 8
  memory: 24G

test_task:
  env:
    CIRRUS_CLONE_DEPTH: 50
    CIRRUS_WORKING_DIR: /workspace
  info_script: bazel version
  test_script: |
    bazel test \
      --spawn_strategy=sandboxed \
      --strategy=Javac=sandboxed \
      --genrule_strategy=sandboxed \
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST \
      //tenserflow/...
