timeout_in: 2h


container:
  dockerfile: tensorflow/tools/ci_build/Dockerfile.cpu
  cpu: 8
  memory: 24G

env:
  CIRRUS_CLONE_DEPTH: 50
  CIRRUS_WORKING_DIR: /workspace
  DOCKER_CONTEXT: tensorflow/tools/ci_build/

task:  
  name: Test (Remote Cache)
  test_script: |
    bazel test \
      --spawn_strategy=sandboxed \
      --strategy=Javac=sandboxed \
      --genrule_strategy=sandboxed \
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST \
      //tensorflow/...

task:  
  name: Test (No Caching)
  test_script: bazel test //tensorflow/...
